PackageIdentifier: Headlamp.Headlamp
PackageVersion: 0.19.1
Installers:
  - Architecture: x64
    InstallerLocale: en-US
    InstallerType: exe
    InstallerUrl: https://github.com/headlamp-k8s/headlamp/releases/download/v0.19.1/Headlamp-0.19.1-win-x64.exe
    InstallerSha256: 42bb36fca7d973c21d659935228719d454f74a2ccb2f4ec21c7ec492bc6ab7aa
    Scope: user
    InstallModes:
      - interactive
      - silent
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
    AppsAndFeaturesEntries:
      - DisplayName: Headlamp
        DisplayVersion: 0.19.1
        Publisher: Headlamp
        InstallerType: exe
    ReleaseDate: 2023-24-08
ManifestType: installer
ManifestVersion: 1.5.0