PackageIdentifier: Headlamp.Headlamp
PackageVersion: 0.19.1
PackageLocale: en-US
Publisher: Headlamp
PublisherUrl: https://headlamp.dev
PackageName: Headlamp
License: Apache 2.0
LicenseUrl: https://github.com/headlamp-k8s/headlamp/blob/main/LICENSE
ShortDescription: Kubernetes web UI.
Description: Headlamp was created to be a Kubernetes web UI that has the traditional functionality of other web UIs/dashboards available (i.e. to list and view resources) as well as other features.
Tags:
  - kubernetes
  - plugins
  - kinvolk
  - headlamp
  - dashboard
  - ui
  - web
  - monitoring
  - logging
  - cncf
Documentations:
  - DocumentLabel: headlamp documentation
    DocumentUrl: https://headlamp.dev/docs/latest
ReleaseNotesUrl: https://github.com/headlamp-k8s/headlamp/releases/tag/v0.19.1
ManifestType: defaultLocale
ManifestVersion: 1.5.0